import random

from naff import Extension, slash_command


class dynamic(Extension):
    @slash_command("dynamic", description="inspiration for your next script.")
    async def dynamic(self, ctx):
        coolwordsxd = [
            "3D Tryg",
            "AFK",
            "ATM Machine System",
            "ATM Machine's",
            "ATM System",
            "ATM's",
            "Admin-Vehicle Lock - for all u lazy ppl!!!",
            "Animations",
            "Backpack",
            "Bash",
            "Bazookas System",
            "Biz",
            "Bomb System",
            "Boobs",
            "Business",
            "Business v1.0",
            "Business v1.0-R1",
            "Business v1.0-R2",
            "Business v1.0-R3",
            "Business v1.0-R3.1",
            "Buy Weapon And Kits",
            "Car Ownership System",
            "Categories",
            "Checkpoints",
            "Circles",
            "Company",
            "Dialog Gang Bang System",
            "Dialog Gang System",
            "Dialog Maker",
            "Dildo System",
            "Door System",
            "EPIC HOUSE",
            "EnEx",
            "Entrance",
            "Fire-Bin",
            "GPS",
            "Gang Bang",
            "Gang",
            "Garage",
            "Garbage Collector",
            "Gate",
            "Gates",
            "Guild System",
            "Guild",
            "Hot Coffee",
            "House System",
            "House Creating!",
            "House",
            "House-Biz System",
            "House-Business System",
            "Ice Cream Creation",
            "IconMaker",
            "Interior",
            "Interiors",
            "Job Creation",
            "Large Arrays",
            "Material Text",
            "Media Dialog",
            "Menus",
            "Milf",
            "Milf Gang Bang",
            "Mom",
            "Mom Gang Bang",
            "Myth Creator",
            "News",
            "Org Creation",
            "PISD",
            "Player Account Data",
            "Player Enumerator",
            "Position save system",
            "PowerShell",
            "Race system",
            "Rules ← Using HTTP!",
            "Semi Dynamic System",
            "Server Signature Generator",
            "Short Arrays",
            "Stingers",
            "Stores",
            "Street w/ sign",
            "System",
            "Teleport",
            "Telnet Client",
            "Telnet Server",
            "Update",
            "VEHICLES",
            "Vehicle & Dealership",
            "Vehicle Creator",
            "Vehicle Spawn Menu",
            "Vehicle System",
            "Vertify",
            "Vibrator System",
            "Weapon control",
            "Weapon shop",
        ]

        morewords = [
            " ← USING HTTP!",
            "0.3d Compatible",
            "1 line",
            "3D Label",
            "Can also be used for missions!",
            "DJSON",
            "Draft",
            "Dynamic!",
            "Map icon",
            "MSSQL",
            "MySQL",
            "Object",
            "Pickup",
            "SQL",
            "SQLite",
            "Saves + Loads Through MySQL!",
            "Scripting SpeedArt Video",
            "TextDraw",
            "User Friendly",
            "account vertification",
            "for Roleplay",
            "loading & saving",
            "pisd",
            "semi dynamicness",
            "streamer",
            "with advanced anti db",
            "zcmd",
        ]

        evenmorewords = ["system", "System", "SYSTEM", "[SYSTEM]"]
        evenmorewordsxd = ["dynamic", "Dynamic", "DYNAMIC", "[DYNAMIC]"]

        await ctx.send(
            f"{random.choice(evenmorewordsxd)} {random.choice(coolwordsxd)} {random.choice(evenmorewords)} {random.choice(morewords)}"
        )


def setup(bot):
    # This is called by dis-snek so it knows how to load the Extensions
    dynamic(bot)
