import random

from naff import Extension, slash_command


class gmname(Extension):
    @slash_command(
        "gmname",
        description="generates a professional gamemode name for your next NGG edit.",
    )
    async def gmname(self, ctx):
        coolwordsxd = [
            "advanced",
            "amazeballs",
            "amazing",
            "amk",
            "burger",
            "🍔",
            "edit",
            "elite",
            "exiting",
            "extr3m3",
            "extreme",
            "fucking",
            "fusion",
            "gold",
            "haram",
            "infusion",
            "l33t",
            "mega",
            "mom",
            "open",
            "pisd",
            "platinum",
            "pro",
            "profesional",
            "reloaded",
            "sa-mp server",
            "ultra",
            "wow",
            "xd",
            "xtreme",
            "you're",
            "kungkingkang",
            "mengheran",
            "mengakak",
            "menghadeh",
        ]

        morewords = [
            "abyss",
            "barp-leak",
            "black",
            "clan",
            "community",
            "español",
            "gaming",
            "gang",
            "ginger",
            "group",
            "hackers",
            "killaz",
            "krisk",
            "mom",
            "motherfuckers",
            "open.mp",
            "parkour",
            "pisd",
            "profesionals",
            "pros",
            "rcrp-leak",
            "revolution",
            "shoters",
            "scripters",
            "white",
            "you(them)tubers",
            "mengontol",
            "kontol",
            "pepeq",
        ]

        gamemodes = [
            "deathmatch",
            "derby",
            "dm",
            "freeroam",
            "game",
            "gangbang",
            "gangwars",
            "minigames",
            "pisd",
            "race",
            "racing",
            "roleplay",
            "dmrp",
            "rp",
            "rpg",
            "sex",
            "tdm",
            "war",
        ]

        tags = [
            "0.3.DL",
            "0.3e+",
            "25.000 LINES",
            "ABYSS",
            "BASIC",
            "BEST",
            "BETA",
            "C++",
            "CUSTOM OBJECTS",
            "DYNAMIC",
            "GF EDIT",
            "GO",
            "POWERED BY G00GLE",
            "GODFATHER",
            "HALAL",
            "HARAM",
            "HIRING",
            "IMPROVED",
            "LAGSHOT",
            "LUA",
            "MOMS",
            "MYSQL",
            "NGG",
            "NGRP",
            "OFFICIAL",
            "OPEN.MP",
            "PAWN",
            "PAWNO",
            "PISD",
            "RAKNET",
            "RCRP",
            "REDIS",
            "REFUNDING",
            "ROLEYPLAY",
            "ROLLERPLAYERS ONLY",
            "RUS",
            "SAMPCTL",
            "SCRATCH",
            "SOUTHCLAWS",
            "SSCANF",
            "STRCMP",
            "STRCMP2",
            "STRTOK",
            "STRTOK2",
            "TELNET",
            "UCP",
            "UNIQUE",
            "YLESS",
            "Y_INI",
            "ZCMD",
            "ZOMBIES",
            "MISEBAHXD",
        ]

        await ctx.send(
            f"{random.choice(coolwordsxd)} {random.choice(morewords)} {random.choice(gamemodes)} {random.choice(tags)}"
        )


def setup(bot):
    # This is called by dis-snek so it knows how to load the Extension
    gmname(bot)
